services:
  postgres:
    image: postgres:latest
    container_name: ${PROJECT_NAME}-db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT_EXTERNAL}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

  app:
    image: eclipse-temurin:21-jre
    container_name: ${PROJECT_NAME}-api
    ports:
      - "8080:8080"
    volumes:
      - ./target:/app
    working_dir: /app
    # Dynamically uses the version from .env
    command: java -jar ${PROJECT_NAME}-${APP_VERSION}.jar
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILE}

volumes:
  postgres_data: