spring.application.name=scoutbase
logging.level.root=INFO
logging.level.com.scoutbase=DEBUG

# Force all logs to console
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n

# JPA/Hibernate configuration
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

# PostgreSQL
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5431/scoutbase-db}
spring.datasource.username=${DATABASE_USERNAME:scoutbadmin}
spring.datasource.password=${DATABASE_PASSWORD:grup5ioc}
spring.datasource.driver-class-name=org.postgresql.Driver