spring.application.name=scoutbase
logging.level.root=INFO
logging.level.com.scoutbase=DEBUG

# Banner
spring.main.banner-mode=console

# Force all logs to console
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%X{sessionId}] %logger{36} - %msg%n

# JPA/Hibernate configuration
spring.jpa.hibernate.ddl-auto=update

# GENERAL rule of the SQL logger
spring.jpa.show-sql=true
# SPECIFIC rule of the Hibernate SQL logger.
# ejemplo de log -> select p1_0.id,p1_0.email,p1_0.name,p1_0.team from player p1_0
spring.jpa.properties.hibernate.show_sql=false

# PostgreSQL config
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5431/scoutbase-local-db}
spring.datasource.username=${DATABASE_USERNAME:postgres}
spring.datasource.password=${DATABASE_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

# Swagger
springdoc.api-docs.enabled=true
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html

# Spring Security (JWT)
security.jwt.secret=${JWT_SECRET:mysupersecretmegatopepasswordLOCAL}
security.jwt.expiration-ms=86400000